
# MySQL.
[database]
	debug   = true
    link    = "mysql:root:12345678@tcp(127.0.0.1:3306)/test?parseTime=true&loc=Local"
    MaxOpen = 100

# Redis.
[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1"

#[database]
#   [[database.default]]
#        type = "mysql"
#        link = "root:12345678@tcp(127.0.0.1:3306)/test?parseTime=true&loc=Local"
#





